#ifndef QUI_CORE_VERSION_H_
#define QUI_CORE_VERSION_H_

#define QUI_VERSION_MAJOR 1
#define QUI_VERSION_MINOR 0
#define QUI_VERSION_PATCH 0
#define QUI_VERSION_SUFFIX ""
#define QUI_VERSION_NAME "qui"

#define QUI_VERSION    ((QUI_VERSION_MAJOR << 16) | (QUI_VERSION_MINOR << 8) | QUI_VERSION_PATCH)

#endif   // QUI_CORE_VERSION_H_
